using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LinkshellManagerDiscordApp.Migrations
{
    /// <inheritdoc />
    public partial class AddAttendanceWindows : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent raw SQL so this migration is safe to apply against a database where
            // Program.cs's EnsureLiveEventSchemaAsync raw-SQL bootstrap has already created
            // these objects.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""EventAttendanceWindows"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""EventId"" integer NOT NULL,
                    ""SequenceNumber"" integer NOT NULL,
                    ""Label"" character varying(64) NULL,
                    ""PostedAt"" timestamp with time zone NOT NULL,
                    ""PostedBySource"" character varying(64) NULL,
                    ""DkpAmount"" double precision NULL,
                    CONSTRAINT ""FK_EventAttendanceWindows_Events_EventId""
                        FOREIGN KEY (""EventId"") REFERENCES ""Events"" (""Id"") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_EventAttendanceWindows_EventId_SequenceNumber""
                    ON ""EventAttendanceWindows"" (""EventId"", ""SequenceNumber"");

                CREATE TABLE IF NOT EXISTS ""AppUserEventWindows"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""AppUserEventId"" integer NOT NULL,
                    ""EventAttendanceWindowId"" integer NOT NULL,
                    ""VerifiedAt"" timestamp with time zone NOT NULL,
                    ""VerifiedBy"" character varying(256) NULL,
                    CONSTRAINT ""FK_AppUserEventWindows_AppUserEvents_AppUserEventId""
                        FOREIGN KEY (""AppUserEventId"") REFERENCES ""AppUserEvents"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_AppUserEventWindows_EventAttendanceWindows_EventAttendanceW~""
                        FOREIGN KEY (""EventAttendanceWindowId"") REFERENCES ""EventAttendanceWindows"" (""Id"") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_AppUserEventWindows_AppUserEventId_EventAttendanceWindowId""
                    ON ""AppUserEventWindows"" (""AppUserEventId"", ""EventAttendanceWindowId"");

                CREATE INDEX IF NOT EXISTS ""IX_AppUserEventWindows_EventAttendanceWindowId""
                    ON ""AppUserEventWindows"" (""EventAttendanceWindowId"");

                ALTER TABLE ""AppUserEventStatusLedgers"" ADD COLUMN IF NOT EXISTS ""EventAttendanceWindowId"" integer NULL;

                CREATE INDEX IF NOT EXISTS ""IX_AppUserEventStatusLedgers_EventAttendanceWindowId""
                    ON ""AppUserEventStatusLedgers"" (""EventAttendanceWindowId"");

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'FK_AppUserEventStatusLedgers_EventAttendanceWindows_EventAtten~'
                    ) THEN
                        ALTER TABLE ""AppUserEventStatusLedgers""
                            ADD CONSTRAINT ""FK_AppUserEventStatusLedgers_EventAttendanceWindows_EventAtten~""
                            FOREIGN KEY (""EventAttendanceWindowId"")
                            REFERENCES ""EventAttendanceWindows"" (""Id"")
                            ON DELETE SET NULL;
                    END IF;
                END$$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_AppUserEventStatusLedgers_EventAttendanceWindows_EventAtten~",
                table: "AppUserEventStatusLedgers");

            migrationBuilder.DropTable(
                name: "AppUserEventWindows");

            migrationBuilder.DropTable(
                name: "EventAttendanceWindows");

            migrationBuilder.DropIndex(
                name: "IX_AppUserEventStatusLedgers_EventAttendanceWindowId",
                table: "AppUserEventStatusLedgers");

            migrationBuilder.DropColumn(
                name: "EventAttendanceWindowId",
                table: "AppUserEventStatusLedgers");
        }
    }
}
