using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinkshellManagerDiscordApp.Migrations
{
    /// <inheritdoc />
    public partial class AddAddonApiAndLedgerSource : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent raw SQL so this migration is safe to apply against a database where
            // Program.cs's EnsureLiveEventSchemaAsync raw-SQL bootstrap has already created
            // these objects.
            migrationBuilder.Sql(@"
                ALTER TABLE ""AppUserEventStatusLedgers"" ADD COLUMN IF NOT EXISTS ""Source"" character varying(32) NULL;

                CREATE TABLE IF NOT EXISTS ""AddonApiTokens"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""LinkshellId"" integer NOT NULL,
                    ""IssuedToAppUserId"" character varying(450) NULL,
                    ""TokenHash"" character varying(128) NOT NULL,
                    ""TokenPrefix"" character varying(16) NOT NULL,
                    ""Label"" character varying(128) NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""LastUsedAt"" timestamp with time zone NULL,
                    ""RevokedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""FK_AddonApiTokens_Linkshells_LinkshellId""
                        FOREIGN KEY (""LinkshellId"") REFERENCES ""Linkshells"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_AddonApiTokens_AspNetUsers_IssuedToAppUserId""
                        FOREIGN KEY (""IssuedToAppUserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE SET NULL
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_AddonApiTokens_TokenHash""
                    ON ""AddonApiTokens"" (""TokenHash"");
                CREATE INDEX IF NOT EXISTS ""IX_AddonApiTokens_LinkshellId""
                    ON ""AddonApiTokens"" (""LinkshellId"");
                CREATE INDEX IF NOT EXISTS ""IX_AddonApiTokens_IssuedToAppUserId""
                    ON ""AddonApiTokens"" (""IssuedToAppUserId"");

                CREATE TABLE IF NOT EXISTS ""AddonPairingCodes"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Code"" character varying(16) NOT NULL,
                    ""LinkshellId"" integer NOT NULL,
                    ""IssuedToAppUserId"" character varying(450) NULL,
                    ""Label"" character varying(128) NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""ExpiresAt"" timestamp with time zone NOT NULL,
                    ""ConsumedAt"" timestamp with time zone NULL,
                    ""ConsumedTokenId"" integer NULL,
                    CONSTRAINT ""FK_AddonPairingCodes_Linkshells_LinkshellId""
                        FOREIGN KEY (""LinkshellId"") REFERENCES ""Linkshells"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_AddonPairingCodes_AspNetUsers_IssuedToAppUserId""
                        FOREIGN KEY (""IssuedToAppUserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE SET NULL
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_AddonPairingCodes_Code""
                    ON ""AddonPairingCodes"" (""Code"");
                CREATE INDEX IF NOT EXISTS ""IX_AddonPairingCodes_ExpiresAt""
                    ON ""AddonPairingCodes"" (""ExpiresAt"");
                CREATE INDEX IF NOT EXISTS ""IX_AddonPairingCodes_LinkshellId""
                    ON ""AddonPairingCodes"" (""LinkshellId"");
                CREATE INDEX IF NOT EXISTS ""IX_AddonPairingCodes_IssuedToAppUserId""
                    ON ""AddonPairingCodes"" (""IssuedToAppUserId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AddonApiTokens");

            migrationBuilder.DropTable(
                name: "AddonPairingCodes");

            migrationBuilder.DropColumn(
                name: "Source",
                table: "AppUserEventStatusLedgers");
        }
    }
}
