// <auto-generated />
using System;
using System.Collections.Generic;
using LinkshellManagerDiscordApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinkshellManagerDiscordApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AddonApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuedToAppUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("IssuedToAppUserId");

                    b.HasIndex("LinkshellId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("AddonApiTokens", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AddonPairingCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ConsumedTokenId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuedToAppUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IssuedToAppUserId");

                    b.HasIndex("LinkshellId");

                    b.ToTable("AddonPairingCodes", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnnouncementDetails")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("AnnouncementTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByAppUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CreatedByCharacterName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.Property<string>("LinkshellName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("LinkshellId", "CreatedAt");

                    b.ToTable("Announcements", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("CharacterName")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("PrimaryLinkshellId")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryLinkshellName")
                        .HasColumnType("text");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("bytea");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AppUserEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<string>("CharacterName")
                        .HasColumnType("text");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EventDkp")
                        .HasColumnType("double precision");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsOnBreak")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQuickJoin")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("JobName")
                        .HasColumnType("text");

                    b.Property<string>("JobType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PauseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Proctor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResumeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubJobName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("EventId");

                    b.ToTable("AppUserEvents");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AppUserEventHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<string>("CharacterName")
                        .HasColumnType("text");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<double?>("EventDkp")
                        .HasColumnType("double precision");

                    b.Property<int>("EventHistoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsQuickJoin")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("JobName")
                        .HasColumnType("text");

                    b.Property<string>("JobType")
                        .HasColumnType("text");

                    b.Property<string>("Proctor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubJobName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("EventHistoryId");

                    b.ToTable("AppUserEventHistories");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AppUserEventStatusLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("AppUserEventId")
                        .HasColumnType("integer");

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeniedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeniedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("EventAttendanceWindowId")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequiresVerification")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("EventAttendanceWindowId");

                    b.HasIndex("EventId");

                    b.HasIndex("AppUserEventId", "OccurredAt");

                    b.ToTable("AppUserEventStatusLedgers", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AppUserEventWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserEventId")
                        .HasColumnType("integer");

                    b.Property<int>("EventAttendanceWindowId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Zone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("EventAttendanceWindowId");

                    b.HasIndex("AppUserEventId", "EventAttendanceWindowId")
                        .IsUnique();

                    b.ToTable("AppUserEventWindows", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AppUserLinkshell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<string>("CharacterName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateJoined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LinkshellDkp")
                        .HasColumnType("double precision");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.Property<string>("Rank")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("LinkshellId");

                    b.ToTable("AppUserLinkshells");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuctionTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinkshellId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AuctionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuctionTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinkshellId");

                    b.ToTable("AuctionHistories");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AuctionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuctionHistoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentHighestBid")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentHighestBidder")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CurrentHighestBidderAppUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EndingBidDkp")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ItemType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("SourceItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StartingBidDkp")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionHistoryId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("SourceItemId");

                    b.ToTable("AuctionItems");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("AuctionItemId")
                        .HasColumnType("integer");

                    b.Property<int>("BidAmount")
                        .HasColumnType("integer");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("AuctionItemId", "CreatedAt");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.DiscordActivityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("GlobalName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.HasIndex("IdentityUserId");

                    b.ToTable("DiscordActivityUsers", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.DkpLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<string>("CharacterName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Details")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("EventEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EventHistoryId")
                        .HasColumnType("integer");

                    b.Property<string>("EventLocation")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EventStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ItemName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("EventHistoryId");

                    b.HasIndex("LinkshellId", "AppUserId", "OccurredAt", "Sequence");

                    b.ToTable("DkpLedgerEntries", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CommencementStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreationSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int?>("DkpPerHour")
                        .HasColumnType("integer");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EventDkp")
                        .HasColumnType("double precision");

                    b.Property<string>("EventLocation")
                        .HasColumnType("text");

                    b.Property<string>("EventName")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WindowCountOverride")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LinkshellId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.EventAttendanceWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("DkpAmount")
                        .HasColumnType("double precision");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostedBySource")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("EventAttendanceWindows", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.EventHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CommencementStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int?>("DkpPerHour")
                        .HasColumnType("integer");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EventDkp")
                        .HasColumnType("double precision");

                    b.Property<string>("EventLocation")
                        .HasColumnType("text");

                    b.Property<string>("EventName")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinkshellId");

                    b.ToTable("EventHistories");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.EventLootDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .HasColumnType("text");

                    b.Property<string>("ItemWinner")
                        .HasColumnType("text");

                    b.Property<int?>("WinningDkpSpent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventLootDetails");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Invite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("LinkshellId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByAppUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CreatedByCharacterName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ItemType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.Property<string>("LinkshellName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinkshellId", "ItemName");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<List<string>>("Enlisted")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("JobName")
                        .HasColumnType("text");

                    b.Property<string>("JobType")
                        .HasColumnType("text");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("SignedUp")
                        .HasColumnType("integer");

                    b.Property<string>("SubJobName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Linkshell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("DkpRoundingIncrement")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("EnableAuctions")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableDkp")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableEndgame")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableEvents")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableHnmSection")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableItems")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableMissions")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableRevenue")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableToDs")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkshellName")
                        .HasColumnType("text");

                    b.Property<string>("LootStructure")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Linkshells");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.LinkshellRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAddLoot")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanAuditDkp")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanCustomizeLinkshell")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageAnnouncements")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageAuctions")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageEvents")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageInventory")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageMembers")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageRoles")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageRules")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageTods")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageTreasury")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanModerateLiveEvent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LinkshellId", "Name")
                        .IsUnique();

                    b.ToTable("LinkshellRoles", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<string>("CharacterNameSender")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotificationDetails")
                        .HasColumnType("text");

                    b.Property<string>("NotificationType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.RevenueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByAppUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CreatedByCharacterName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Details")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.Property<string>("LinkshellName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LinkshellId", "OccurredAt");

                    b.ToTable("RevenueEntries", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByAppUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CreatedByCharacterName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.Property<string>("LinkshellName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RuleDetails")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("RuleTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("LinkshellId", "CreatedAt");

                    b.ToTable("Rules", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Tod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Claim")
                        .HasColumnType("boolean");

                    b.Property<string>("Cooldown")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Interval")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("LinkshellId")
                        .HasColumnType("integer");

                    b.Property<string>("MonsterName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("RepopTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TotalClaims")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalTods")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LinkshellId", "MonsterName");

                    b.HasIndex("LinkshellId", "Time");

                    b.ToTable("Tods", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.TodLootDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("ActualDeductedDkp")
                        .HasColumnType("double precision");

                    b.Property<string>("ItemName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ItemWinner")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("TodId")
                        .HasColumnType("integer");

                    b.Property<int?>("WinningDkpSpent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TodId");

                    b.ToTable("TodLootDetails", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AddonApiToken", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", "IssuedToAppUser")
                        .WithMany()
                        .HasForeignKey("IssuedToAppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany()
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssuedToAppUser");

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AddonPairingCode", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", "IssuedToAppUser")
                        .WithMany()
                        .HasForeignKey("IssuedToAppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany()
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssuedToAppUser");

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Announcement", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany()
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AppUserEvent", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", "AppUser")
                        .WithMany("AppUserEvents")
                        .HasForeignKey("AppUserId");

                    b.HasOne("LinkshellManagerDiscordApp.Models.Event", "Event")
                        .WithMany("AppUserEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AppUserEventHistory", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", "AppUser")
                        .WithMany("AppUserEventHistories")
                        .HasForeignKey("AppUserId");

                    b.HasOne("LinkshellManagerDiscordApp.Models.EventHistory", "EventHistory")
                        .WithMany("AppUserEventHistories")
                        .HasForeignKey("EventHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("EventHistory");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AppUserEventStatusLedger", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUserEvent", "AppUserEvent")
                        .WithMany("StatusLedgerEntries")
                        .HasForeignKey("AppUserEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinkshellManagerDiscordApp.Models.EventAttendanceWindow", "EventAttendanceWindow")
                        .WithMany()
                        .HasForeignKey("EventAttendanceWindowId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinkshellManagerDiscordApp.Models.Event", "Event")
                        .WithMany("StatusLedgerEntries")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("AppUserEvent");

                    b.Navigation("Event");

                    b.Navigation("EventAttendanceWindow");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AppUserEventWindow", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUserEvent", "AppUserEvent")
                        .WithMany("AttendedWindows")
                        .HasForeignKey("AppUserEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkshellManagerDiscordApp.Models.EventAttendanceWindow", "EventAttendanceWindow")
                        .WithMany("Attendees")
                        .HasForeignKey("EventAttendanceWindowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUserEvent");

                    b.Navigation("EventAttendanceWindow");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AppUserLinkshell", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", "AppUser")
                        .WithMany("AppUserLinkshells")
                        .HasForeignKey("AppUserId");

                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany("AppUserLinkshells")
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Auction", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany()
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AuctionHistory", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany()
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AuctionItem", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AuctionHistory", "AuctionHistory")
                        .WithMany("AuctionItems")
                        .HasForeignKey("AuctionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LinkshellManagerDiscordApp.Models.Auction", "Auction")
                        .WithMany("AuctionItems")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LinkshellManagerDiscordApp.Models.Item", "SourceItem")
                        .WithMany()
                        .HasForeignKey("SourceItemId");

                    b.Navigation("Auction");

                    b.Navigation("AuctionHistory");

                    b.Navigation("SourceItem");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Bid", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinkshellManagerDiscordApp.Models.AuctionItem", "AuctionItem")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("AuctionItem");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.DiscordActivityUser", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.DkpLedgerEntry", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinkshellManagerDiscordApp.Models.EventHistory", "EventHistory")
                        .WithMany()
                        .HasForeignKey("EventHistoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany()
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("EventHistory");

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Event", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany("Events")
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.EventAttendanceWindow", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.Event", "Event")
                        .WithMany("AttendanceWindows")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.EventHistory", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany("EventHistories")
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.EventLootDetail", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.Event", "Event")
                        .WithMany("EventLootDetails")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Invite", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany()
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Item", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany()
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Job", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.Event", "Event")
                        .WithMany("Jobs")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Linkshell", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.LinkshellRole", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany()
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Notification", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", "AppUser")
                        .WithMany("Notifications")
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.RevenueEntry", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany()
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Rule", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany()
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Tod", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.Linkshell", "Linkshell")
                        .WithMany()
                        .HasForeignKey("LinkshellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linkshell");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.TodLootDetail", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.Tod", "Tod")
                        .WithMany("TodLootDetails")
                        .HasForeignKey("TodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Tod");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LinkshellManagerDiscordApp.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AppUser", b =>
                {
                    b.Navigation("AppUserEventHistories");

                    b.Navigation("AppUserEvents");

                    b.Navigation("AppUserLinkshells");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AppUserEvent", b =>
                {
                    b.Navigation("AttendedWindows");

                    b.Navigation("StatusLedgerEntries");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Auction", b =>
                {
                    b.Navigation("AuctionItems");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AuctionHistory", b =>
                {
                    b.Navigation("AuctionItems");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.AuctionItem", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Event", b =>
                {
                    b.Navigation("AppUserEvents");

                    b.Navigation("AttendanceWindows");

                    b.Navigation("EventLootDetails");

                    b.Navigation("Jobs");

                    b.Navigation("StatusLedgerEntries");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.EventAttendanceWindow", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.EventHistory", b =>
                {
                    b.Navigation("AppUserEventHistories");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Linkshell", b =>
                {
                    b.Navigation("AppUserLinkshells");

                    b.Navigation("EventHistories");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("LinkshellManagerDiscordApp.Models.Tod", b =>
                {
                    b.Navigation("TodLootDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
